- hosts: localhost
  name: configuration
  user: fedora
  become: yes
  become_user: root
  gather_facts: true

  tasks:
          -   name: Install python setup tools
              dnf: name=python-setuptools
              tags: docker

          -   name: Install git
              dnf: name=git
              tags: docker

          -   name: Install Pypi
              easy_install: name=pip
              tags: docker

          -   name: Install docker-py
              pip: name=docker-py
              tags: docker

          -   name: Install Docker
              dnf: name=docker state=latest
              tags: docker

          -   name: Make sure Docker is running
              service: name=docker state=running enabled=yes
              tags: docker

          -   name: Install -> Docker-Compose
              sudo: yes
              get_url:
                url=https://github.com/docker/compose/releases/download/1.10.0/docker-compose-Linux-x86_64
                dest=/usr/local/bin/docker-compose
                mode=0755

          - name: Install list of packages
            dnf: name={{item}} state=installed
            with_items:
                - which
                - findutils
                - procps-ng
                - git
                - gnupg2
                - docker-engine
                - patch
                - redhat-rpm-config
                - libyaml-devel
                - glibc-headers
                - autoconf
                - gcc-c++
                - glibc-devel
                - readline-devel
                - zlib-devel
                - libffi-devel
                - openssl-devel
                - make
                - bzip2
                - automake
                - libtool
                - bison
                - sqlite-devel
                - ruby
                - ruby-devel
                - libxml2-devel

          -  name: setup directory for limecompiler
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/opt/limecompiler
               state=directory
               mode=770

          -  name: checkout latest from git of Limecompiler
             git:
               repo=https://github.com/ThreatResponse/lime-compiler.git
               dest=/opt/limecompiler
               update=yes

          -  name: setup directory build
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/opt/limecompiler/build
               state=directory
               mode=770

          -  name: setup directory for modules
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/opt/limecompiler/build/modules
               state=directory
               mode=770

          -  name: setup directory for archive
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/opt/limecompiler/archive
               state=directory
               mode=770

          -  name: change /opt/limecompiler permissions
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/opt/limecompiler
               state=directory
               recurse=yes

          -  name: ensure exec permissions
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/home/fedora/01-sync.sh
               mode=770

          -  name: ensure exec permissions
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/home/fedora/02-build.sh
               mode=774

          -  name: ensure exec permissions
             sudo: yes
             file:
               owner=fedora
               group=fedora
               path=/home/fedora/03-sync.sh
               mode=770

          -  name: create docker group
             sudo: yes
             group:
               name=docker

          -  name: add fedora user to docker group
             sudo: yes
             user:
               name=fedora
               groups=docker
               append=yes

        #  - name: Set SELinux to Permissive for build
        #    selinux: policy=targeted state=permissive
